language: csharp
solution: MailDependencyInjection.sln

matrix:
  include:
    - mono: latest
      env: PROJ=Mono
    - dotnet: 2.1.502
      mono: none
      env: PROJ=Core

if: PROJ=Mono

  install:
    - nuget restore MailDependencyInjection.sln

  script:
    - msbuild /p:Configuration=Release MailDependencyInjection.sln

if: PROJ=Core

  install:
    - dotnet restore 

  script:
    - dotnet build
