language: csharp
solution: MailDependenciyInjection.sln

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
    - mono: latest

install:
  - nuget restore MailDependenciyInjection.sln
script:
  - msbuild /p:Configuration=Release MailDependenciyInjection.sln