language: csharp
solution: MailDependencyInjection.sln

matrix:
  include:
    - mono: latest

install:
  - nuget restore MailDependencyInjection.sln

script:
  - msbuild /p:Configuration=Release MailDependencyInjection.sln