language: csharp
solution: MailDependencyInjection.sln

matrix:
  include:
    - mono: latest
      env: PROJ=Mono
    - dotnet: 2.1.502
      mono: none
      env: PROJ=Core
  install:
    if: PROJ=Mono 
      - nuget restore MailDependencyInjection.sln
    if: PROJ=Core
      - dotnet restore
  script:
    if: PROJ=Mono
      - msbuild /p:Configuration=Release MailDependencyInjection.sln
    if: PROJ=Core
    - dotnet build
