language: csharp
solution: MailDependencyInjection.sln

matrix:
  include:
    - mono: latest
      env: PROJ=Mono
    - dotnet: 2.1.502
      mono: none
      env: PROJ=Core
  install:
      - nuget restore MailDependencyInjection.sln
      - dotnet restore
  script:
      - msbuild /p:Configuration=Release MailDependencyInjection.sln
      - dotnet build
